// 25 Beispiel-Datensätze als Vorlage
const baseData = [
  {
    id: 1,
    name: "John Doe",
    email: "john.doe@example.com",
    provider: "google",
    is_admin: true,
    created_at: "2024-01-15T10:30:00Z",
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    provider: "github",
    is_admin: false,
    created_at: "2024-02-20T14:15:00Z",
  },
  {
    id: 3,
    name: "Bob Johnson",
    email: "bob.johnson@example.com",
    provider: "email",
    is_admin: false,
    created_at: "2024-03-10T09:45:00Z",
  },
  {
    id: 4,
    name: "Alice Williams",
    email: "alice.williams@example.com",
    provider: "google",
    is_admin: true,
    created_at: "2024-01-05T16:20:00Z",
  },
  {
    id: 5,
    name: "Charlie Brown",
    email: "charlie.brown@example.com",
    provider: "github",
    is_admin: false,
    created_at: "2024-04-12T11:30:00Z",
  },
  {
    id: 6,
    name: "Diana Prince",
    email: "diana.prince@example.com",
    provider: "google",
    is_admin: true,
    created_at: "2024-05-18T13:25:00Z",
  },
  {
    id: 7,
    name: "Ethan Hunt",
    email: "ethan.hunt@example.com",
    provider: "email",
    is_admin: false,
    created_at: "2024-06-22T08:50:00Z",
  },
  {
    id: 8,
    name: "Fiona Gallagher",
    email: "fiona.gallagher@example.com",
    provider: "github",
    is_admin: false,
    created_at: "2024-07-14T15:40:00Z",
  },
  {
    id: 9,
    name: "George Miller",
    email: "george.miller@example.com",
    provider: "google",
    is_admin: false,
    created_at: "2024-08-03T10:15:00Z",
  },
  {
    id: 10,
    name: "Hannah Montana",
    email: "hannah.montana@example.com",
    provider: "email",
    is_admin: true,
    created_at: "2024-09-11T14:30:00Z",
  },
  {
    id: 11,
    name: "Isaac Newton",
    email: "isaac.newton@example.com",
    provider: "github",
    is_admin: false,
    created_at: "2024-10-05T09:20:00Z",
  },
  {
    id: 12,
    name: "Julia Roberts",
    email: "julia.roberts@example.com",
    provider: "google",
    is_admin: false,
    created_at: "2024-11-18T16:45:00Z",
  },
  {
    id: 13,
    name: "Kevin Hart",
    email: "kevin.hart@example.com",
    provider: "email",
    is_admin: false,
    created_at: "2024-12-02T11:10:00Z",
  },
  {
    id: 14,
    name: "Laura Croft",
    email: "laura.croft@example.com",
    provider: "github",
    is_admin: true,
    created_at: "2024-01-22T13:55:00Z",
  },
  {
    id: 15,
    name: "Michael Scott",
    email: "michael.scott@example.com",
    provider: "google",
    is_admin: false,
    created_at: "2024-02-14T08:30:00Z",
  },
  {
    id: 16,
    name: "Nancy Drew",
    email: "nancy.drew@example.com",
    provider: "email",
    is_admin: false,
    created_at: "2024-03-25T15:20:00Z",
  },
  {
    id: 17,
    name: "Oscar Wilde",
    email: "oscar.wilde@example.com",
    provider: "github",
    is_admin: true,
    created_at: "2024-04-30T10:40:00Z",
  },
  {
    id: 18,
    name: "Pamela Anderson",
    email: "pamela.anderson@example.com",
    provider: "google",
    is_admin: false,
    created_at: "2024-05-12T14:15:00Z",
  },
  {
    id: 19,
    name: "Quentin Tarantino",
    email: "quentin.tarantino@example.com",
    provider: "email",
    is_admin: false,
    created_at: "2024-06-08T09:50:00Z",
  },
  {
    id: 20,
    name: "Rachel Green",
    email: "rachel.green@example.com",
    provider: "github",
    is_admin: false,
    created_at: "2024-07-19T16:25:00Z",
  },
  {
    id: 21,
    name: "Steven Universe",
    email: "steven.universe@example.com",
    provider: "google",
    is_admin: true,
    created_at: "2024-08-27T11:35:00Z",
  },
  {
    id: 22,
    name: "Tina Turner",
    email: "tina.turner@example.com",
    provider: "email",
    is_admin: false,
    created_at: "2024-09-15T13:10:00Z",
  },
  {
    id: 23,
    name: "Uma Thurman",
    email: "uma.thurman@example.com",
    provider: "github",
    is_admin: false,
    created_at: "2024-10-21T10:05:00Z",
  },
  {
    id: 24,
    name: "Victor Hugo",
    email: "victor.hugo@example.com",
    provider: "google",
    is_admin: false,
    created_at: "2024-11-09T15:45:00Z",
  },
  {
    id: 25,
    name: "Wendy Williams",
    email: "wendy.williams@example.com",
    provider: "email",
    is_admin: true,
    created_at: "2024-12-16T09:30:00Z",
  },
];

// 250 Datensätze generieren
export const data = Array.from({ length: 1500 }, (_, i) => {
  const base = baseData[i % baseData.length];
  // ID eindeutig, Name und Email leicht variieren, Datum pro Block verschieben
  return {
    ...base,
    id: i + 1,
    name: `${base.name} ${Math.floor(i / baseData.length) + 1}`,
    email: base.email.replace("@", `.${Math.floor(i / baseData.length) + 1}@`),
    created_at: new Date(
      new Date(base.created_at).getTime() +
        1000 * 60 * 60 * 24 * 30 * Math.floor(i / baseData.length)
    ).toISOString(),
  };
});
